title: J.C. Britton Publishing
email: jcbritton@protonmail.com
description: Indie press & editing studio for sci-fi, paranormal, religious & philosophical stories.
url: "https://jcbrittonpublishing.github.io"
logo: /assets/images/tattoo-logo.svg
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# defaults:
#  - scope:
#      path: ""
#    values:
#      image: /assets/images/tattoo-logo.svg
